//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexReplacer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexReplacer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace in files from regular expressions.
        ///
        ///Usage: {0}
        ///
        ///Switches:
        ///{1}.
        /// </summary>
        internal static string CommandLine_Help {
            get {
                return ResourceManager.GetString("CommandLine_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command line argument(s) &quot;{0}&quot; unknown.
        /// </summary>
        internal static string CommandLine_UnknownArgs {
            get {
                return ResourceManager.GetString("CommandLine_UnknownArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory can&apos;t be undefined.
        /// </summary>
        internal static string RegexReplacer_DirectoryUndefined {
            get {
                return ResourceManager.GetString("RegexReplacer_DirectoryUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace error occurred:
        /// {0}
        ///
        ///Try &apos;--help&apos; for more information..
        /// </summary>
        internal static string RegexReplacer_Error {
            get {
                return ResourceManager.GetString("RegexReplacer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of modified files: {0}.
        /// </summary>
        internal static string RegexReplacer_NbModifiedFiles {
            get {
                return ResourceManager.GetString("RegexReplacer_NbModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid regular expression: {0}.
        /// </summary>
        internal static string RegexReplacer_RegexInvalid {
            get {
                return ResourceManager.GetString("RegexReplacer_RegexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search regex can&apos;t be undefined.
        /// </summary>
        internal static string RegexReplacer_RegexUndefined {
            get {
                return ResourceManager.GetString("RegexReplacer_RegexUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace value can&apos;t be null.
        /// </summary>
        internal static string RegexReplacer_ReplaceNull {
            get {
                return ResourceManager.GetString("RegexReplacer_ReplaceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ####################################
        ///&gt; Input directory: {0}
        ///&gt; File search pattern: {1}
        ///&gt; Find regex: {2}
        ///&gt; Replace: {3}
        ///&gt; Mode: {4}
        ///####################################.
        /// </summary>
        internal static string RegexReplacer_Summary {
            get {
                return ResourceManager.GetString("RegexReplacer_Summary", resourceCulture);
            }
        }
    }
}
